### ISSUE TITLE
doesn't find anyone now

### ISSUE THREAD

**Issue by Drifty96** [ThePotato97/RoSearcher#13]
doesn't find anyone but i think roblox just fucked things up. would be cool if u found a fix tho

**Comment by ThePotato97** [comment]
Can you share any more details on this issue?

**Comment by ThePotato97** [comment]
https://user-images.githubusercontent.com/10260415/165447867-7a68aa0b-f100-4b74-ac6e-663c5db78313.mp4

**Comment by ThePotato97** [comment]
What is the username of the account that you're trying to Rosearch?

**Comment by forkergirosea** [comment]
same for me. 
![изображение](https://user-images.githubusercontent.com/108001380/175026035-af51488a-0f45-4c77-aa34-8ea9cc373c4b.png)
stuck on this part.

**Comment by Xeon-E** [comment]
> What is the username of the account that you're trying to Rosearch?

If you watch the video, you can tell it is a 1 player server and Im assuming he went ingame and copied one the players ingame name to test it, proving the extension does not work. Ever since the new UI got implemented I encountered problems such as this. 
I found an error in console:
![image_2022-06-26_190815387](https://user-images.githubusercontent.com/83479315/175837257-bda21d35-cd9a-4ceb-83cd-918f88a5faa4.png)
